function love.conf(t)
	t.identity = "vPet"
	t.appendidentity = false
	t.version = 11.2
	t.console = false
	t.accelerometerjoystick = false
	t.externalstorage = false
	t.gammacorrect = false
	t.audio.mixwithsystem = true
	t.window.title = "Virtual Pet"
	t.window.icon = nil
	t.window.width = 600
	t.window.height = 600
	t.window.borderless = false
	t.window.resizable = false
	t.window.fullscreen = false
	t.window.vsync = 0
	t.window.highdpi = false
	t.modules.audio = false
	t.modules.data = true
	t.modules.event = true
	t.modules.font = true
	t.modules.graphics = true
	t.modules.image = true
	t.modules.joystick = false
	t.modules.keyboard = true
	t.modules.math = true
	t.modules.mouse = true
	t.modules.physics = false
	t.modules.sound = false --might want to change
	t.modules.thread = true
	t.modules.timer = true
	t.modules.touch = true
	t.modules.video = true
	t.modules.window = true
end